<script type="text/javascript">
	    Ext.onReady(function() {
        // sample static data for the store
        var sourceStore  = new Ext.data.JsonStore({
         extend: 'Ext.data.Model',
                fields: [
                   {name: 'kd_admin',type: 'string'},
                   {name: 'nama_admin',type: 'string'},
                   {name: 'email_admin',type: 'string'},
                   {name: 'no_hp_admin',type: 'string'}
                ],
          autoLoad: true,
          proxy:{
            type:'ajax',
            url:'<?php echo $this->baseUrl('/admin/getadmin'); ?>',
            reader:{
                 type:'json',
                 root:'users'
                }
            }

        });
        this.sourceStore = sourceStore; 
        var rowEditing = Ext.create('Ext.grid.plugin.RowEditing', {
        clicksToMoveEditor: 1,
        autoCancel: false,
        listeners: {
        validateedit: function(editor,e,opt){
                        $.ajax({
                            url: '<?php echo $this->baseUrl()?>/admin/updatejson',
                            type: 'post',
                            data: { data : JSON.stringify( e.newValues ) }, // Our valid JSON string
                            success: function( data, status, xhr ) {
                                Ext.Msg.alert("Alert", "Update Data Berhasil.");
                                sourceStore.load(); 
                            },
                            error: function( xhr, status, error ) {
                               Ext.Msg.alert("Alert", "Update Data Gagal.");
                            }
                        });   
        }
       }
        });
        var simple = Ext.widget({
         xtype: 'form',
        layout: 'form',
        collapsible: false,
        id: 'admin',
        frame: true,
        title: 'Tambah Akun',
        method:'POST',
        width: 600,
        renderTo: 'tambah-admin',
        defaultType: 'textfield',
        items: [
        {
            fieldLabel: 'Username',
            type : 'text',
            name: 'username',
            allowBlank: false,
        },
        {
            fieldLabel: 'Password',
            type : 'text',
            name: 'password',
            inputType: 'password',
            allowBlank: false,
        },
        {
            fieldLabel: 'Nama',
            type : 'text',
            name: 'nama',
            allowBlank: false,
        },
        {
            fieldLabel: 'email',
            type : 'text',
            name: 'email',
            vtype:'email',
            allowBlank: false,
        },
        {
            fieldLabel: 'Nomor HP',
            type : 'text',
            name: 'nomor',
            allowBlank: false,
        },
        ],

        buttons: [
        {
            type: 'submit',
            text: 'Tambah',
            handler: function(){ insert(); }
        }],

    });
      var insert = function(){
      if(simple.getForm().isValid()){
                Ext.Msg.confirm("Confirmation", "Do you want to Tambah changes?", function(btnText){
                            if(btnText === "no"){
                                Ext.Msg.alert("Alert", "You have confirmed 'Tambah'.");
                            }
                            else if(btnText === "yes"){
                               simple.getForm().submit({
                  method:'POST',
                  url: '<?php echo $this->baseUrl() ?>/admin/insert',
                  waitMsg: 'Processing Request',
                  failure:function(form, action){
                    if(action.response.responseText == '"Success"'){
                        Ext.Msg.alert('Berhasil', 'Tambah Akun', Ext.emptyFn);
                        sourceStore.load();                                          
                    }else{
                       Ext.Msg.alert('Salah', 'gagal Tambah', Ext.emptyFn);
                    }
                    simple.getForm().reset();
                }


              });
                                
                            }
                        }, this);
              

        }
          };

        var grid = Ext.create('Ext.grid.Panel', {
            renderTo: document.body,
            plugins: [rowEditing],
            store :sourceStore,
            tbar: toolbaradmin,
            stateful: true,
            collapsible: false,
            multiSelect: true,
            stateId: 'stateGrid',
            columns: [
                {
                    header     : 'Kode Admin',
                    flex     : 1,
                    sortable : false,
                    dataIndex: 'kd_admin',
                },
                {
                    header     : 'Nama Admin',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'nama_admin',
                    field: {
                    xtype: 'textfield'
                    }
                },
                {
                    header     : 'Email Admin',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'email_admin',
                    field: {
                    xtype: 'textfield'
                    }
                },
                {
                    header     : 'Nomor HP',
                    width    : 85,
                    sortable : true,
                    dataIndex: 'no_hp_admin',
                    field: {
                    xtype: 'textfield'
                    }
                },
                
                {
                    header     : 'Action',
                    menuDisabled: false,
                    sortable: false,
                    xtype: 'actioncolumn',
                    width: 50,
                    items: [{
                        icon   : '<?php echo $this->baseUrl(); ?>/extjs/examples/shared/icons/fam/delete.gif',  // Use a URL in the icon config
                        tooltip: 'Delete',
                        handler: function(grid, rowIndex, colIndex) {
                           Ext.Msg.confirm("Confirmation", "Do you want to Delete changes?", function(btnText){
                            if(btnText === "no"){
                                Ext.Msg.alert("Alert", "You have confirmed 'No'.");
                            }
                            else if(btnText === "yes"){
                                 var rec = sourceStore.getAt(rowIndex);
                                 Ext.Ajax.request({
                                    method: 'POST',
                                    url: '<?php echo $this->baseUrl('/admin/delete/') ?>',
                                    standardSubmit: true,
                                    disableCaching: false,
                                    id  : 'deleteget',
                                    success: function(response, opts) {
                                        
                                        if(response.responseText == '"Failed"'){
                                            Ext.Msg.alert('alert', 'Data Tidak');                                                   
                                        }else{
                                            Ext.Msg.alert('alert', 'Data Berhasil Di hapus');
                                            sourceStore.load();
                                        }                    
                                    },
                                    failure: function() {
                                        Ext.Msg.alert('', 'failed');
                                    },
                                    params: {
                                        action: 'delete',
                                        name : rec.get('kd_admin'),
                                    }
                                });
                                
                            }
                        }, this);
                     
                            
                        }
                    }
                    ]
                }
            ], 
            height: 350,
            width: 600,
            title: 'Table Admin',
            renderTo: 'grid-admin',
            viewConfig: {
            stripeRows: true,
            enableTextSelection: true,
            }
        });
    });
    
    var toolbaradmin = Ext.create('Ext.toolbar.Toolbar', {
    id : 'form-id',
    renderTo: document.body,
    xtype: 'form',
    method: 'POST',
    width   : 50,
    frame: true,
    items: [{
            text: 'Reload Data',
            handler : function(){
            sourceStore.load(); 
            }
            },
        // begin using the right-justified button container
        '->', // same as { xtype: 'tbfill' }
        {
        xtype     : 'combobox',
        emptyText: 'Cari Berdasarkan',
            id      : 'get',
        store     : ['Kode',
                        'Nama',
                        'Email',
                        'Nomor'
                        ],
            listeners: {
              select: function(text){
//               Ext.Msg.alert('alert', 'Cari Data ' +text.lastValue);  
              // console.log(text.lastValue);
              }
            }
        },
        
        {
            xtype    : 'textfield',
            name     : 'search',
            type    : 'text',
            emptyText: 'Cari Data',
            id      : 'search',
        },          
        {   
            icon   : '<?php echo $this->baseUrl(); ?>/extjs/docs/resources/images/preview.png',
            type: 'submit',
            handler: function(){ 
            Ext.Ajax.request({
                method: 'GET',
                url: '<?php echo $this->baseUrl('/admin/search/') ?>',
                standardSubmit: true,
                disableCaching: false,
                id  : 'cariget',
                success: function(response, opts) {
                    
                    if(response.responseText == '"kosong"'){
                        Ext.Msg.alert('alert', 'Data Tidak');                                                   
                    }else{
                        sourceStore.clearData();
                        sourceStore.loadRawData(Ext.JSON.decode(response.responseText), true);

                    }                    
                },
                failure: function() {
                    Ext.Msg.alert('', 'failed');
                },
                params: {
                    action: Ext.getCmp('get').getValue(),
                    name : Ext.getCmp('search').getValue(),
                }
            });
        }        
        }
    ]
}); 
</script>
<div align="left" id="tambah-admin"></div>
            <br>
            <div align="left" id="grid-admin"></div>
            