<script type="text/javascript">
        Ext.onReady(function() {

        // sample static data for the store
        var storedep  = new Ext.data.JsonStore({
         extend: 'Ext.data.Model',
                fields: [
                   {name: 'kd_department',type: 'string'},
                   {name: 'nama_department',type: 'string'},
                ],
          autoLoad: true,
          proxy:{
            type:'ajax',
            url:'<?php echo $this->baseUrl('/hr/dep'); ?>',
            reader:{
                 type:'json',
                 root:'dep'
                }
            }

        });
        this.storedep = storedep; 
        var rowEditingDep = Ext.create('Ext.grid.plugin.RowEditing', {
        clicksToMoveEditor: 1,
        autoCancel: false,
        listeners: {
        validateedit: function(editor,e,opt){
                        $.ajax({
                            url: '<?php echo $this->baseUrl()?>/hr/updatedep',
                            type: 'post',
                            data: { data : JSON.stringify( e.newValues ) }, // Our valid JSON string
                            success: function( data, status, xhr ) {
                                storedep.load();
                                Ext.Msg.alert("Alert", "Update Data Berhasil.");
                            },
                            error: function( xhr, status, error ) {
                               Ext.Msg.alert("Alert", "Update Data Gagal.");
                            }
                        });   
            }
        }
        });
        var tambahdep = Ext.widget({
         xtype: 'form',
        layout: 'form',
        collapsible: false,
        frame: true,
        title: 'Tambah Department',
        method:'POST',
        width: 600,
        renderTo: 'tambah-department',
        defaultType: 'textfield',
        items: [
        {
            fieldLabel: 'Nama Devisi',
            type : 'text',
            name: 'nama',
            allowBlank: false,
        },
        ],

        buttons: [
        {
            type: 'submit',
            text: 'Tambah',
            handler: function(){ insertdep(); }
        }],

    });
      var insertdep = function(){
      if(tambahdep.getForm().isValid()){
                Ext.Msg.confirm("Confirmation", "Do you want to Tambah changes?", function(btnText){
                if(btnText === "no"){
                    Ext.Msg.alert("Alert", "You have confirmed 'Tambah'.");
                }
                else if(btnText === "yes"){
                  tambahdep.getForm().submit({
                  method:'POST',
                  url: '<?php echo $this->baseUrl() ?>/hr/insertdep',
                  waitMsg: 'Processing Request',
                  failure:function(form, action){
                    if(action.response.responseText == '"Success"'){
                        Ext.Msg.alert('Berhasil', 'Tambah Department', Ext.emptyFn);
                        storedep.load();                                          
                    }else{
                       Ext.Msg.alert('Salah', 'gagal Tambah', Ext.emptyFn);
                    }
                    tambahdep.getForm().reset();
                }


              });
                            }
                        }, this);
            }
        };

        var griddep = Ext.create('Ext.grid.Panel', {
            plugins: [rowEditingDep],
            store :storedep,
            tbar: toolbardep,
            stateful: true,
            collapsible: false,
            multiSelect: true,
            stateId: 'stateGrid',
            columns: [
                {
                    header     : 'Kode Department',
                    flex     : 1,
                    sortable : false,
                    dataIndex: 'kd_department',
                },
                {
                    header     : 'Nama Department',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'nama_department',
                    field: {
                    xtype: 'textfield'
                    }
                },
                {
                    header     : 'Action',
                    menuDisabled: false,
                    sortable: false,
                    xtype: 'actioncolumn',
                    width: 50,
                    items: [{
                        icon   : '<?php echo $this->baseUrl(); ?>/extjs/examples/shared/icons/fam/delete.gif',  // Use a URL in the icon config
                        tooltip: 'Delete',
                        handler: function(grid, rowIndex, colIndex) {
                           Ext.Msg.confirm("Confirmation", "Do you want to Delete changes?", function(btnText){
                            if(btnText === "no"){
                                Ext.Msg.alert("Alert", "You have confirmed 'No'.");
                            }
                            else if(btnText === "yes"){
                                 var rec = storedep.getAt(rowIndex);
                                 Ext.Ajax.request({
                                    method: 'POST',
                                    url: '<?php echo $this->baseUrl('/hr/deletedep/') ?>',
                                    standardSubmit: true,
                                    disableCaching: false,
                                    id  : 'deleteget',
                                    success: function(response, opts) {
                                        
                                        if(response.responseText == '"Failed"'){
                                            Ext.Msg.alert('alert', 'Data Tidak');                                                   
                                        }else{
                                            Ext.Msg.alert('alert', 'Data Berhasil Di hapus');
                                            storedep.load();
                                        }                    
                                    },
                                    failure: function() {
                                        Ext.Msg.alert('', 'Gagal Terhubung Server Database');
                                    },
                                    params: {
                                        action: 'delete',
                                        name : rec.get('kd_department'),
                                    }
                                });
                                
                            }
                        }, this);
                     
                            
                        }
                    }
                    ]
                }
            ], 
            height: 350,
            width: 600,
            title: 'Table Department',
            renderTo: 'grid-department',
            viewConfig: {
            stripeRows: true,
            enableTextSelection: true,
            }
        });
    });
    
    var toolbardep = Ext.create('Ext.toolbar.Toolbar', {
    id : 'dep-id',
    renderTo: document.body,
    xtype: 'form',
    method: 'POST',
    width   : 50,
    frame: true,
    items: [{
            text: 'Reload Data',
            handler : function(){
            storedep.load(); 
            }
        },
        // begin using the right-justified button container
        '->', // same as { xtype: 'tbfill' }
        {
        xtype     : 'combobox',
        emptyText: 'Cari Berdasarkan',
        id      : 'getdep',
        store     : ['Kode',
                    'Department',
                    ],
        listeners: {
              select: function(text){
//               Ext.Msg.alert('alert', 'Cari Data ' +text.lastValue);  
              // console.log(text.lastValue);
              }
            }
        },
        
        {
            xtype    : 'textfield',
            name     : 'search',
            type    : 'text',
            emptyText: 'Cari Data',
            id      : 'searchdep',
        },          
        {   
            icon   : '<?php echo $this->baseUrl(); ?>/extjs/docs/resources/images/preview.png',
            type: 'submit',
            handler: function(){ 
            Ext.Ajax.request({
                method: 'GET',
                url: '<?php echo $this->baseUrl('/hr/searchdep/') ?>',
                standardSubmit: true,
                disableCaching: false,
                id  : 'cariget',
                success: function(response, opts) {
                    
                    if(response.responseText == '"kosong"'){
                        Ext.Msg.alert('alert', 'Data Tidak');                                                   
                    }else{
                        storedep.clearData();
                        storedep.loadRawData(Ext.JSON.decode(response.responseText), true);
                    }                    
                },
                failure: function() {
                    Ext.Msg.alert('', 'failed');
                },
                params: {
                    action: Ext.getCmp('getdep').getValue(),
                    name : Ext.getCmp('searchdep').getValue(),
                }
            });
        }        
        }
    ]
}); 
</script>
 <div align="left" id="tambah-department"></div>
            <br>
            <div align="left" id="grid-department"></div>
        