<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>QDC</title>
        <link REL="SHORTCUT ICON" HREF="<?php echo $this->baseUrl() ?>/favicon.ico">
        <!-- Ext -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/extjs/resources/css/ext-all.css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/extjs/ext-all.js"></script>
        <!-- example code -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/erp/menu.css">
        <!-- GC -->
        <!-- page specific -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

        <script type="text/javascript">
        Ext.Loader.setPath('Ext.ux', '<?php echo $this->baseUrl('/extjs/examples/ux/') ?>');
        //
        // This is the main layout definition.
        //
        Ext.onReady(function(){
         
            Ext.tip.QuickTipManager.init();

            // This is an inner body element within the Details panel created to provide a "slide in" effect
            // on the panel body without affecting the body's box itself.  This element is created on
            // initial use and cached in this var for subsequent access.            
            // Gets all layouts examples

            
            // This is the main content center region that will contain each example layout panel.
            // It will be implemented as a CardLayout since it will contain multiple panels with
            // only one being visible at any given time.

            var contentPanel = {
                 id: 'content-panel',
                 region: 'center', // this is what makes this panel into a region within the containing layout
                 layout: 'fit',
                 title: 'Home Page',
                 autoScroll: true,
                 bodyPadding: 15,
                 contentEl: 'start-div',
                 
            };
             
            var store = Ext.create('Ext.data.TreeStore', {
                root: {
                    expanded: true
                },
                proxy: {
                    type: 'ajax',
                    url: '<?php echo $this->baseUrl() ?>/erp/tree-navbar.json'
                }
            });
            
            // Go ahead and create the TreePanel now so that we can use it below
             var treePanel = Ext.create('Ext.tree.Panel', {
                id: 'tree-panel',
                title: 'Navigation',
                region:'north',
                split: true,
                collapsible: true,
                height: 360,
                minSize: 150,
                rootVisible: false,
                autoScroll: true,
                store: store,
                loadMask: {msg: 'Loading...'},


            });
            // Assign the changeLayout function to be called on tree node click.
            treePanel.getSelectionModel().on('select', function(selModel, record) {
                
                if (record.get('leaf')) {
                    var itemid = record.get('id');
                    Ext.get("content-panel").load({
                        url:"<?php echo $this->baseUrl('/menu/') ?>" + itemid,
                        text:"loading",
                        scripts:true
                    });
                }   
            });
            
            // This is the Details panel that contains the description for each example layout.
            var detailsPanel = {
                id: 'details-panel',
                title: 'Notification',
                region: 'center',
                bodyStyle: 'padding-bottom:15px;background:#eee;',
                autoScroll: true,
                html: '<p class="details-info">Helo World</p>'
            };
         
            // Finally, build the main layout once all the pieces are ready.  This is also a good
            // example of putting together a full-screen BorderLayout within a Viewport.
            Ext.create('Ext.Viewport', {
                layout: 'border',
                title: 'Ext Layout Browser',
                items: [
                {
                    xtype: 'box',
                    id: 'header',
                    region: 'north',
                    html: '<h1> <b align="center"> Hai, <?php echo $this->user ?></b><a href="<?php echo $this->baseUrl('/menu') ?>"><button>Home</button></a><a href="<?php echo $this->baseUrl('/login/logout') ?>"><button>Logout</button></a></h1>',
                    height: 30
                },
                {
                    layout: 'border',
                    id: 'layout-browser',
                    region:'west',
                    border: false,
                    split:true,
                    margins: '2 0 5 5',
                    width: 275,
                    minSize: 100,
                    maxSize: 500,
                    items: [treePanel, detailsPanel]
                }, 
                    contentPanel
                ],
                renderTo: Ext.getBody()
            });
        });

</script>
<!-- <?php echo $this->render('menu/admin.phtml');?>
    <?php echo $this->render('menu/department.phtml');?>
    <?php echo $this->render('menu/jabatan.phtml'); ?> -->
    </head>
<body>
     <!-- Pretty loading mask -->
    <div id="loading-mask"></div>
    <div id="loading">
      <div class="loading-indicator">
        Loading...
      </div>
    </div>
    
    <div style="display:none;">
        <!-- Start page content -->
        <div id="start-div">
            <div style="float:left;" ><img src="http://erp.qdc.co.id/images/qdc.png" /></div>
            <div style="margin-left:100px;">
                <h2>Welcome!</h2>
                <p>This is QDC ERP on web, current state : Production.</p>
            </div>
        </div>
    </div>
</body>