<script type="text/javascript">
	 Ext.onReady(function() {

        Ext.tip.QuickTipManager.init();

        // sample static data for the store
        var storejab  = new Ext.data.JsonStore({
         extend: 'Ext.data.Model',
                fields: [
                   {name: 'kd_jabatan',type: 'string'},
                   {name: 'nama_department',type: 'string'},
                   {name: 'nama_jabatan',type: 'string'},
                ],
          autoLoad: true,
          proxy:{
            type:'ajax',
            url:'<?php echo $this->baseUrl('/hr/jab'); ?>',
            reader:{
                 type:'json',
                 root:'jab'
                }
            }

        });
        var getdepstore  = new Ext.data.JsonStore({
         extend: 'Ext.data.Model',
                fields: [
                   {name: 'kd_department',type: 'string'},
                   {name: 'nama_department',type: 'string'},
                ],
          autoLoad: true,
          autoDestroy: true,
          proxy:{
            type:'ajax',
            url:'<?php echo $this->baseUrl('/hr/dep'); ?>',
            reader:{
                 type:'json',
                 root:'dep'
                }
            },
        });
        this.getdepstore = getdepstore; 
        this.storejab = storejab; 
        var rowEditingJab = Ext.create('Ext.grid.plugin.RowEditing', {
        clicksToMoveEditor: 1,
        autoCancel: false,
        listeners: {
        validateedit: function(editor,e,opt){
                        $.ajax({
                            url: '<?php echo $this->baseUrl()?>/hr/updatejab',
                            type: 'post',
                            data: { data : JSON.stringify( e.newValues ) }, // Our valid JSON string
                            success: function( data, status, xhr ) {
                                Ext.Msg.alert("Alert", "Update Data Berhasil.");
                                storejab.load();
                            },
                            error: function( xhr, status, error ) {
                               Ext.Msg.alert("Alert", "Update Data Gagal.");
                            }
                        });   
                     }
        }
        });
        var tambahjab = new Ext.form.FormPanel ({
        xtype: 'form',
        layout: 'form',
        collapsible: false,
        frame: true,
        title: 'Tambah Jabatan',
        method:'POST',
        width: 750,
        renderTo: 'tambah-jab',
        defaultType: 'textfield',
        items: [
        {
            fieldLabel: 'Pilih Devisi',
            queryMode: 'remote',
            typeAhead: true,
            id : 'combodev',
            forceSelection: true,
            displayField: 'nama_department', // <-- Add this 
            valueField: 'kd_department',
            type : 'text',
            xtype : 'combo',
            name: 'devisi',
            triggerAction: 'all',
            emptyText: 'Pilih Devisi',
            store : getdepstore,
            selectOnFocus: true, 
            listeners: {
                expand: function() {
                    getdepstore.load();
                }
            }
        },
        {
            fieldLabel: 'Nama jabatan',
            type : 'text',
            name: 'jabatan',
            allowBlank: false,
        },
        ],

        buttons: [
        {
            type: 'submit',
            text: 'Tambah',
            handler: function(){ insertjab(); }
        }],

    });
      var insertjab = function(){
      if(tambahjab.getForm().isValid()){
                Ext.Msg.confirm("Confirmation", "Do you want to Tambah changes?", function(btnText){
                if(btnText === "no"){
                    Ext.Msg.alert("Alert", "You have confirmed 'Tambah'.");
                }
                else if(btnText === "yes"){
                  tambahjab.getForm().submit({
                  method:'POST',
                  url: '<?php echo $this->baseUrl() ?>/hr/insertjab',
                  waitMsg: 'Processing Request',
                  failure:function(form, action){
                    if(action.response.responseText == '"Success"'){
                        Ext.Msg.alert('Berhasil', 'Tambah Jabatan', Ext.emptyFn);
                        storejab.load();                                          
                    }else{
                       Ext.Msg.alert('Salah', 'gagal Tambah', Ext.emptyFn);
                    }
                    tambahjab.getForm().reset();
                }


              });
                            }
                        }, this);
        }
          };
        var search  =  [
            ["kd_jabatan", "Kode"],
            ["nama_department", "Department"],
            ["nama_jabatan", "Jabatan"]
            ]
        var combo1 = new Ext.form.ComboBox({
            store: search,
            displayField: 'nama_search', // <-- Add this 
            valueField: 'kd_search',
            typeAhead: true,
            mode: 'local',
            triggerAction: 'all',
            selectOnFocus: true,
            name: 'option',
            width: 100,
            style: 'margin-left: 5px',
            // emptyText: 'Cari Berdasarkan',
            value : 'Kode',
            id: 'getjab1'
        });
        var combo2 = new Ext.form.ComboBox({
            store: search,
            displayField: 'nama_search', // <-- Add this 
            valueField: 'kd_search',
            typeAhead: true,
            mode: 'local',
            triggerAction: 'all',
            selectOnFocus: true,
            name: 'option',
            width: 100,
            style: 'margin-left: 10px',
            emptyText: 'Cari Berdasarkan',
            id: 'getjab2'
        });
        var gridjab = Ext.create('Ext.grid.Panel', {
            plugins: [rowEditingJab],
            store :storejab,
            bbar: new Ext.PagingToolbar({
                id: 'paging',
                pageSize: 30,
                store: storejab,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            }),
            tbar: [
            {
                xtype: 'tbtext',
                text: 'Search By',
                style: 'margin-left: 5px'
            },
            combo1,
            {
                xtype: 'textfield',
                id: 'searchjab1',
                style: 'margin-left: 10px;margin-right:10px',
                enableKeyEvents: true,
            },
            combo2,
            {
                xtype: 'textfield',
                id: 'searchjab2',
                style: 'margin-left: 10px;margin-right:10px',
                enableKeyEvents: true,
            },
            {   
                icon   : '<?php echo $this->baseUrl(); ?>/extjs/docs/resources/images/preview.png',
                type: 'submit',
                handler: function(){ 
                Ext.Ajax.request({
                    method: 'GET',
                    url: '<?php echo $this->baseUrl('/hr/searchjab/') ?>',
                    standardSubmit: true,
                    disableCaching: false,
                    id  : 'cariget',
                    success: function(response, opts) {
                    
                        if(response.responseText == '"kosong"'){
                            Ext.Msg.alert('alert', 'Data Tidak');                                                   
                        }else{
                            storejab.clearData();
                            storejab.loadRawData(Ext.JSON.decode(response.responseText), true);
                        }                    
                    },
                    failure: function() {
                        Ext.Msg.alert('', 'failed');
                    },
                    params: {
                        action1 : Ext.getCmp('getjab1').getValue(),
                        action2 : Ext.getCmp('getjab2').getValue(),
                        search1 : Ext.getCmp('searchjab1').getValue(),
                        search2 : Ext.getCmp('searchjab2').getValue(),
                    }
                });
              }        
            },
            {
                text: 'Reload Data',
                handler: refreshData,
                scope: this
            }
            ],
            stateful: true,
            collapsible: false,
            multiSelect: true,
            stateId: 'stateGrid',
            columns: [
                {
                    header     :'Kode Jabatan',
                    flex     : 1,
                    sortable : false,
                    dataIndex: 'kd_jabatan',
                },
                {
                    header     :'Nama Department',
                    width    : 75,
                    sortable : false,
                    dataIndex: 'nama_department',
                    field: {
                    xtype: 'textfield',
                    queryMode: 'local',
                    typeAhead: true,
                    forceSelection: true,
                    displayField: 'nama_department', // <-- Add this 
                    valueField: 'kd_department',
                    xtype : 'combo',
                    name: 'devisi',
                    emptyText: 'Pilih Devisi',
                    store : getdepstore,
                    }
                },
                 {
                    header     :'Nama Jabatan',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'nama_jabatan',
                    field: {
                    xtype: 'textfield',
                    }
                },
                {
                    header     : 'Action',
                    menuDisabled: false,
                    sortable: false,
                    xtype: 'actioncolumn',
                    width: 50,
                    items: [{
                        icon   : '<?php echo $this->baseUrl(); ?>/extjs/examples/shared/icons/fam/delete.gif',  // Use a URL in the icon config
                        tooltip: 'Delete',
                        handler: function(grid, rowIndex, colIndex) {
                           Ext.Msg.confirm("Confirmation", "Do you want to Delete changes?", function(btnText){
                            if(btnText === "no"){
                                Ext.Msg.alert("Alert", "You have confirmed 'No'.");
                            }
                            else if(btnText === "yes"){
                                 var rec = storejab.getAt(rowIndex);
                                 Ext.Ajax.request({
                                    method: 'POST',
                                    url: '<?php echo $this->baseUrl('/hr/deletejab/') ?>',
                                    standardSubmit: true,
                                    disableCaching: false,
                                    id  : 'deleteget',
                                    success: function(response, opts) {
                                        storejab.load();
                                        if(response.responseText == '"Failed"'){
                                            Ext.Msg.alert('alert', 'Data Tidak');                                                   
                                        }else{
                                            Ext.Msg.alert('alert', 'Data Berhasil Di hapus');
                                        }                    
                                    },
                                    failure: function() {
                                        Ext.Msg.alert('', 'Gagal Terhubung Server Database');
                                    },
                                    params: {
                                        action: 'delete',
                                        name : rec.get('kd_jabatan'),
                                    }
                                });
                                
                            }
                        }, this);
                     
                            
                        }
                    }
                    ]
                }
            ], 
            height: 350,
            width: 780,
            title: 'Table Jabatan',
            renderTo: 'grid-jab',
            viewConfig: {
            stripeRows: true,
            enableTextSelection: true,
            }
            });
    function refreshData()
        {
            storejab.clearFilter();
            Ext.getCmp('searchjab1').setValue('');
            Ext.getCmp('searchjab2').setValue('');
            Ext.getCmp('paging').doRefresh();
        }
    });

    var container = new Ext.Container({
            items: [
                {
                    title: 'jabatan',
                    layout: 'fit',
                    autoScroll: true,
                    bodyPadding: 15,
                    contentEl : 'jabatan-div'
                }
            ],
            autoWidth: true,
            height: 400,
            renderTo: 'container-jabatan'
        });
</script>
<div id="container-jabatan">
    <div id="jabatan-div">
        <div id="tambah-jab"></div>
        <br>
        <div id="grid-jab"></div>
    </div>
</div>
          