<script type="text/javascript">
     Ext.onReady(function() {

        Ext.tip.QuickTipManager.init();

        // sample static data for the store
        var store  = new Ext.data.JsonStore({
         extend: 'Ext.data.Model',
                fields: [
                   {name: 'kd_jabatan',type: 'string'},
                   {name: 'nama_department',type: 'string'},
                   {name: 'nama_jabatan',type: 'string'},
                   {name: 'desc_department',type: 'string'},
                ],
          autoLoad: true,
          proxy:{
            type:'ajax',
            url:'<?php echo $this->baseUrl('/hr/jab'); ?>',
            reader:{
                 type:'json',
                 root:'jab'
                }
            }

        });
        
        var gridjab = Ext.create('Ext.grid.Panel', {
            store :store,
             tbar: [
            {
                xtype: 'button',
                text: 'Download Excel',
                style: 'margin-left: 5px',
                handler: function()
                    {
                        location.href = '<?php echo $this->baseUrl() ?>/hr/exportexcel';

                    }
            }],
            stateful: true,
            collapsible: false,
            multiSelect: true,
            stateId: 'stateGrid',
            columns: [
                {
                    header     :'Kode Jabatan',
                    flex     : 1,
                    sortable : false,
                    dataIndex: 'kd_jabatan',
                },
                {
                    header     :'Nama Department',
                    width    : 75,
                    sortable : false,
                    dataIndex: 'nama_department',
                },
                {
                    header     :'Nama Jabatan',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'nama_jabatan',
                },
                {
                    header     :'Description',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'desc_department',
                },
            ], 
            height: 350,
            width: 780,
            title: 'Table Jabatan',
            renderTo: 'grid',
            viewConfig: {
            stripeRows: true,
            enableTextSelection: true,
            }
            });

    var container = new Ext.Container({
            items: [
                {
                    title: 'report',
                    layout: 'fit',
                    autoScroll: true,
                    bodyPadding: 15,
                    contentEl : 'report-div'
                }
            ],
            autoWidth: true,
            height: 400,
            renderTo: 'container-report'
        });
    });
</script>
<div id="container-report">
    <div id="report-div">
        <div id="grid"></div>
    </div>
</div>
          