<script type="text/javascript">
     Ext.onReady(function() {

        Ext.tip.QuickTipManager.init();

        // sample static data for the store
        var store  = new Ext.data.JsonStore({
         extend: 'Ext.data.Model',
                fields: [
                   {name: 'kd_jabatan',type: 'string'},
                   {name: 'nama_department',type: 'string'},
                   {name: 'nama_jabatan',type: 'string'},
                   {name: 'desc_department',type: 'string'},
                ],
          autoLoad: true,
          proxy:{
            type:'ajax',
            url:'<?php echo $this->baseUrl('/hr/jab'); ?>',
            reader:{
                 type:'json',
                 root:'jab'
                }
            }

        });
        var search  =  [
            ["nama_department", "Department"],
            ["nama_jabatan", "Jabatan"]
            ]
        var combo1 = new Ext.form.ComboBox({
            store: [["kd_jabatan", "Kode"]],
            displayField: 'nama_search', // <-- Add this 
            valueField: 'kd_search',
            typeAhead: true,
            mode: 'local',
            triggerAction: 'all',
            selectOnFocus: true,
            name: 'option',
            width: 100,
            style: 'margin-left: 5px',
            // emptyText: 'Cari Berdasarkan',
            value : 'Kode',
            id: 'getjab1'
        });
        var combo2 = new Ext.form.ComboBox({
            store: search,
            displayField: 'nama_search', // <-- Add this 
            valueField: 'kd_search',
            typeAhead: true,
            mode: 'local',
            triggerAction: 'all',
            selectOnFocus: true,
            name: 'option',
            width: 100,
            style: 'margin-left: 10px',
            emptyText: 'Cari Berdasarkan',
            id: 'getjab2'
        });
        var gridjab = Ext.create('Ext.grid.Panel', {
            store :store,
            tbar: [
            {
                text: 'Reload Data',
                handler: refreshData,
                scope: this
            },
            combo1,
            {
                xtype: 'textfield',
                id: 'searchjab1',
                style: 'margin-left: 10px;margin-right:10px',
                enableKeyEvents: true,
            },
            combo2,
            {
                xtype: 'textfield',
                id: 'searchjab2',
                style: 'margin-left: 10px;margin-right:10px',
                enableKeyEvents: true,
            },
            {   
                icon   : '<?php echo $this->baseUrl(); ?>/extjs/docs/resources/images/preview.png',
                type: 'submit',
                text : 'Show',
                handler: function(){ 
                Ext.Ajax.request({
                    method: 'GET',
                    url: '<?php echo $this->baseUrl('/hr/searchjab/') ?>',
                    standardSubmit: true,
                    disableCaching: false,
                    id  : 'cariget',
                    success: function(response, opts) {
                    
                        if(response.responseText == '"kosong"'){
                            Ext.Msg.alert('alert', 'Data Tidak');                                                   
                        }else{
                            store.clearData();
                            store.loadRawData(Ext.JSON.decode(response.responseText), true);
                        }                    
                    },
                    failure: function() {
                        Ext.Msg.alert('', 'failed');
                    },
                    params: {
                        action1 : Ext.getCmp('getjab1').getValue(),
                        action2 : Ext.getCmp('getjab2').getValue(),
                        search1 : Ext.getCmp('searchjab1').getValue(),
                        search2 : Ext.getCmp('searchjab2').getValue(),
                    }
                });
              }        
            },

            {
                type: 'submit',
                text: 'Download',
                handler: function(){  download();}
            },
            ],
            stateful: true,
            collapsible: false,
            multiSelect: true,
            stateId: 'stateGrid',
            columns: [
                {
                    header     :'Kode Jabatan',
                    flex     : 1,
                    sortable : false,
                    dataIndex: 'kd_jabatan',
                },
                {
                    header     :'Nama Department',
                    width    : 75,
                    sortable : false,
                    dataIndex: 'nama_department',
                },
                {
                    header     :'Nama Jabatan',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'nama_jabatan',
                },
                {
                    header     :'Description',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'desc_department',
                },
            ], 
            height: 350,
            width: 780,
            title: 'Table Report',
            renderTo: 'grid',
            viewConfig: {
            stripeRows: true,
            enableTextSelection: true,
            }
            });
    function refreshData(){
        store.clearFilter();
        store.load();
        Ext.getCmp('searchjab1').setValue('');
        Ext.getCmp('searchjab2').setValue('');
    }
    function download(){
        var param1 = Ext.getCmp('getjab1').getValue();
        var param2 = Ext.getCmp('getjab2').getValue();
        var value1 = Ext.getCmp('searchjab1').getValue();
        var value2 = Ext.getCmp('searchjab2').getValue();
        location.href = '<?php echo $this->baseUrl() ?>/hr/exportexcel/?action1='+ param1 +'&action2='+ param2 +'&search1='+ value1 +'&search2=' + value2 ;
         Ext.Msg.alert('alert', 'Download Berhasil'); 
         grid.clearFilter();
    }
    var container = new Ext.Container({
            items: [
                {
                    title: 'report',
                    layout: 'fit',
                    autoScroll: true,
                    bodyPadding: 15,
                    contentEl : 'report-div'
                }
            ],
            autoWidth: true,
            height: 400,
            renderTo: 'container-report'
        });
    });
</script>
<div id="container-report">
    <div id="report-div">
        <div id="grid"></div>
    </div>
</div>
          