<!-- /*
Fiddle loads js files sequentially and order matters bcz of dependencies
Rearrange files & folder structure in tree if fiddle not working
    FileSaver.js
    Formatter.js
    csvFormatter/*.js
    excelFormatter/*.js
    Exporter.js
    ExporterButton.js
*/ -->
<script type="text/javascript">
     
Ext.Loader.setConfig({
    enabled: true,
    disableCaching: true,
    paths: {
        'Ext.ux.exporter': 'exporter'
    }
});

Ext.application({
    name: 'ExporterDemo',
    requires: ['Ext.ux.exporter.Exporter'],
    launch: function() {
        var myData = <?php echo $this->data ?>;

        // create the data store and load the data
        var store = Ext.create('Ext.data.ArrayStore', {
            fields: [
                   {name: 'kd_jabatan',type: 'string'},
                   {name: 'nama_department',type: 'string'},
                   {name: 'nama_jabatan',type: 'string'},
                   {name: 'desc_department',type: 'string'},
                ],
            data: myData
        });

        Ext.create('Ext.Container', {
            //title: 'Exportable grid Demo',
            layout: 'fit',
            autoScroll: true,
            bodyPadding: 15,
            renderTo: 'grid-report',
            items: [
                {
                xtype: 'grid',
                region: 'center',
                itemId: 'sampleGrid',
                title: 'Report',
                //titleAlign: 'center',
                store: store,
                tbar: [{
                    xtype: 'exporterbutton',
                    text: 'Save As CSV',
                    format: 'excel',
                    component: '#sampleGrid',
                    title: 'Sample'
                    }, 
                ],
                columns: [
                {
                    header     :'Kode Jabatan',
                    flex     : 1,
                    sortable : false,
                    dataIndex: 'kd_jabatan',
                    id: 'kd_jabatan'
                },
                {
                    header     :'Nama Department',
                    width    : 75,
                    sortable : false,
                    dataIndex: 'nama_department',
                },
                {
                    header     :'Nama Jabatan',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'nama_jabatan',
                },
                {
                    header     :'Description',
                    width    : 75,
                    sortable : true,
                    dataIndex: 'desc_department',
                },
                ], 
            }]
        });
    }
});

</script>
<div id="grid-report">

</div>