
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->title; ?></title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/extjs/resources/css/ext-all.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/extjs/examples/shared/example.css" />
    <!-- GC -->
    	<style type="text/css">
		.x-panel {
		    margin:0 auto;
		    text-align:left;

		}
		.x-panel,   
		body.ux-layout-center {            
		    text-align:center;
		}
		</style>
		        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/extjs/ext-all.js"></script>
		        <script type="text/javascript">
		Ext.require([
		    //'Ext.form.*',
		    //'Ext.layout.container.Column',
		    //'Ext.tab.Panel'
		    '*'
		]);

Ext.onReady(function() {
    Ext.QuickTips.init();
    
    var bd = Ext.getBody();

    /*
     * ================  Simple form  =======================
     */

    var required = '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>';

    var simple = Ext.widget({
    	id : 'form-id',
    	frame:true,
	    width:260,
		labelWidth:60,
		defaults: {
	    width: 165
		},
        xtype: 'form',
        layout: 'form',
        method:'POST',
        collapsible: false,
        title: 'LOGIN',
        fieldDefaults: {
            msgTarget: 'side',
        },
        defaultType: 'textfield',
        items: [{
            fieldLabel: 'Username',
            name: 'username',
            type : 'text',
            blankText:"Enter your username",
            allowBlank: false
        },{
            fieldLabel: 'Password',
            name: 'password',
            inputType: 'password',
            blankText:"Enter your password",
            allowBlank: false
        }],

        buttons: [{
        	type: 'submit',
            text: 'login',
            handler: function(){ doLogin(); }
        }]
    });
      var doLogin = function(){
      if(simple.getForm().isValid()){

              simple.getForm().submit({
                  method:'POST',
                  url: '<?php echo $this->url() ?>/ceklogin',
                  waitMsg: 'Processing Request',
                  failure:function(form, action){
                    if(action.response.responseText == '"Success"'){
                    	document.location =  '<?php echo $this->baseUrl() ?>/admin';                                                    
                    }else{
                       Ext.Msg.alert('Login Gagal!', 'username/password salah', Ext.emptyFn);
                    }
                    simple.getForm().reset();
                }


              });

      }

  };
    simple.render(document.body);

});
        </script>
        <br><br><br><br><br><br><br><br><br><b><br><b><br><br>
        <!--<p align="center" >IP Kamu : <?php echo $this->ipaddres; ?></p>-->

    </body>


</html>
