
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->title; ?></title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/extjs/resources/css/ext-all.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/extjs/examples/shared/example.css" />
    <!-- GC -->
    	<style type="text/css">
		.x-panel {
		    margin:0 auto;
		    text-align:left;

		}
		.x-panel,   
		body.ux-layout-center {            
		    text-align:center;
		}
		</style>
		        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/extjs/ext-all.js"></script>
		        <script type="text/javascript">
                
		Ext.require([
		    //'Ext.form.*',
		    //'Ext.layout.container.Column',
		    //'Ext.tab.Panel'
		    '*'
		]);

	Ext.onReady(function() {
    Ext.QuickTips.init();
    
    var bd = Ext.getBody();

    /*
     * ================  Simple form  =======================
     */

    var required = '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>';

    var simple = Ext.widget({
    	 xtype: 'form',
        layout: 'form',
        collapsible: false,
        id: 'simpleForm',
        frame: true,
        title: 'Tambah Form',
        method:'POST',
        width: 350,
        fieldDefaults: {
            msgTarget: 'side',
            labelWidth: 75
        },
        defaultType: 'textfield',
        items: [
        {
            fieldLabel: 'Username',
            type : 'text',
            name: 'username',
            allowBlank: false,
        },
        {
            fieldLabel: 'Password',
            type : 'text',
            name: 'password',
            inputType: 'password',
            allowBlank: false,
        },
        {
            fieldLabel: 'Nama',
            type : 'text',
            name: 'nama',
            allowBlank: false,
        },
        {
            fieldLabel: 'email',
            type : 'text',
            name: 'email',
            allowBlank: false,
        },
        {
            fieldLabel: 'Nomor HP',
            type : 'text',
            name: 'nomor',
            allowBlank: false,
        },
        ],

        buttons: [
        {
        	type: 'submit',
            text: 'Kembali',
            handler: function(){ kembali(); }
        },
        {
            type: 'submit',
            text: 'Tambah',
            handler: function(){ insert(); }
        }],

    });
      var insert = function(){
      if(simple.getForm().isValid()){
                Ext.Msg.confirm("Confirmation", "Do you want to Tambah changes?", function(btnText){
                            if(btnText === "no"){
                                Ext.Msg.alert("Alert", "You have confirmed 'Tambah'.");
                            }
                            else if(btnText === "yes"){
                               simple.getForm().submit({
                  method:'POST',
                  url: '<?php echo $this->baseUrl() ?>/admin/insert',
                  waitMsg: 'Processing Request',
                  failure:function(form, action){
                    console.log(action);
                    if(action.response.responseText == '"Success"'){
                    document.location =  '<?php echo $this->baseUrl() ?>/admin';                                                    
                    }else{
                       Ext.Msg.alert('Salah', 'gagal Tambah', Ext.emptyFn);
                    }
                    simple.getForm().reset();
                }


              });
                                
                            }
                        }, this);
              

}
  };
    simple.render(document.body);
    var kembali = function(){ 
        location.href = "<?php echo $this->baseUrl() ?>/admin";  
     }
});
        </script>
        <h1 align="center">Tambah Akun</h1>
        <!--<p align="center" >IP Kamu : <?php echo $this->ipaddres; ?></p>-->

    </body>


</html>
